name: "Phase 1: Agentic Intake"

# Automatically triage new issues: check for duplicates, gather context, route to appropriate team
on:
  issues:
    types: [opened]

jobs:
  triage:
    name: Analyze New Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install GitHub Copilot CLI
        run: npm install -g @github/copilot

      - name: Get issue details
        id: issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch issue details
          gh api /repos/${{ github.repository }}/issues/${{ github.event.issue.number }} > issue.json

          TITLE=$(jq -r '.title' issue.json)
          BODY=$(jq -r '.body // "No description provided"' issue.json)

          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "Issue title: $TITLE"

      - name: Search for duplicate issues
        id: duplicates
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Searching for potential duplicates..."

          # Search for similar open issues
          TITLE="${{ steps.issue.outputs.title }}"
          gh api --method GET /search/issues \
            -f q="repo:${{ github.repository }} is:issue is:open \"${TITLE}\"" \
            --jq '.items[0:5] | map("- #\(.number): \(.title) (state: \(.state))") | join("\n")' \
            > open-issues.txt || echo "No similar open issues found" > open-issues.txt

          # Search for similar closed issues from last 6 months
          gh api --method GET /search/issues \
            -f q="repo:${{ github.repository }} is:issue is:closed created:>=$(date -d '6 months ago' +%Y-%m-%d) \"${TITLE}\"" \
            --jq '.items[0:5] | map("- #\(.number): \(.title) (closed: \(.closed_at))") | join("\n")' \
            > closed-issues.txt || echo "No similar closed issues found" > closed-issues.txt

          echo "duplicates_found=true" >> $GITHUB_OUTPUT

      - name: Run Copilot CLI for triage analysis
        id: copilot_triage
        env:
          GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
        run: |
          echo "🤖 Running Copilot CLI for issue triage..."

          # Read issue details and duplicates
          ISSUE_BODY=$(jq -r '.body // "No description provided"' issue.json)
          OPEN_ISSUES=$(cat open-issues.txt)
          CLOSED_ISSUES=$(cat closed-issues.txt)

          # Load external prompt template and substitute variables
          sed -e "s|{{ISSUE_NUMBER}}|${{ github.event.issue.number }}|g" \
              -e "s|{{ISSUE_TITLE}}|${{ steps.issue.outputs.title }}|g" \
              -e "s|{{ISSUE_BODY}}|${ISSUE_BODY}|g" \
              -e "s|{{OPEN_ISSUES}}|${OPEN_ISSUES}|g" \
              -e "s|{{CLOSED_ISSUES}}|${CLOSED_ISSUES}|g" \
              .github/prompts/triage-instructions.md > triage_instructions.txt

          # Run Copilot CLI with external instructions
          copilot -p @triage_instructions.txt > triage_result.txt

          # Parse Copilot's output
          cat triage_result.txt

          # Extract key information
          IS_DUPLICATE=$(grep "DUPLICATE:" triage_result.txt | cut -d' ' -f2 || echo "no")
          ISSUE_TYPE=$(grep "TYPE:" triage_result.txt | cut -d' ' -f2 || echo "unknown")
          PRIORITY=$(grep "PRIORITY:" triage_result.txt | cut -d' ' -f2 || echo "medium")

          echo "is_duplicate=$IS_DUPLICATE" >> $GITHUB_OUTPUT
          echo "issue_type=$ISSUE_TYPE" >> $GITHUB_OUTPUT
          echo "priority=$PRIORITY" >> $GITHUB_OUTPUT

      - name: Add labels based on triage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🏷️ Adding labels based on triage results..."

          # Add type label
          TYPE_LABEL="type:${{ steps.copilot_triage.outputs.issue_type }}"
          gh api POST /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
            --input - <<EOF
          {
            "labels": ["${TYPE_LABEL}", "priority:${{ steps.copilot_triage.outputs.priority }}", "status:triaged"]
          }
          EOF

      - name: Post triage results
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Read full triage results
          TRIAGE_RESULT=$(cat triage_result.txt)

          # Post as comment
          gh api POST /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            --input - <<EOF
          {
            "body": "## 🤖 Phase 1: Triage Complete\n\n### Analysis\n\n\`\`\`\n${TRIAGE_RESULT}\n\`\`\`\n\n### Labels Applied\n- Type: \`${{ steps.copilot_triage.outputs.issue_type }}\`\n- Priority: \`${{ steps.copilot_triage.outputs.priority }}\`\n- Status: \`triaged\`\n\n✅ Issue has been triaged and is ready for execution planning.\n\n---\n*Automated by [agentic-journey Phase 1](https://github.com/${{ github.repository }}/tree/main/tech-talks/agentic-journey)*"
          }
          EOF
