name: "Phase 2: Agentic Planning"

# Generate execution plan after triage: research historical issues, analyze codebase, create plan
on:
  issues:
    types: [labeled]

jobs:
  planning:
    name: Generate Plan
    runs-on: ubuntu-latest
    # Only run when status:triaged label is added
    if: github.event.label.name == 'status:triaged'
    permissions:
      issues: write
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install GitHub Copilot CLI
        run: npm install -g @github/copilot

      - name: Get issue details
        id: issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch issue details
          gh api /repos/${{ github.repository }}/issues/${{ github.event.issue.number }} > issue.json

          TITLE=$(jq -r '.title' issue.json)
          BODY=$(jq -r '.body // "No description provided"' issue.json)

          # Save for later use
          echo "$TITLE" > issue_title.txt
          echo "$BODY" > issue_body.txt

          echo "Issue #${{ github.event.issue.number }}: $TITLE"

      - name: Search for historical similar issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "ðŸ” Searching for similar historical issues..."

          TITLE=$(cat issue_title.txt)

          # Search for similar closed issues from last 6 months
          gh api --method GET /search/issues \
            -f q="repo:${{ github.repository }} is:issue is:closed created:>=$(date -d '6 months ago' +%Y-%m-%d) ${TITLE}" \
            --jq '.items[0:5] | map("Issue #\(.number): \(.title)\n  Closed: \(.closed_at)\n  Labels: \(.labels | map(.name) | join(", "))") | join("\n\n")' \
            > similar-issues.txt || echo "No similar issues found" > similar-issues.txt

          echo "Similar issues found:"
          cat similar-issues.txt

      - name: Retrieve PRs from similar issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "ðŸ”— Retrieving PRs associated with similar issues..."

          # Search for merged PRs from last 6 months
          gh api --method GET /search/issues \
            -f q="repo:${{ github.repository }} is:pr is:merged created:>=$(date -d '6 months ago' +%Y-%m-%d)" \
            --jq '.items[0:5] | map("PR #\(.number): \(.title)\n  Merged: \(.closed_at)\n  Files changed: \(.changed_files) | +\(.additions) -\(.deletions)") | join("\n\n")' \
            > related-prs.txt || echo "No related PRs found" > related-prs.txt

          echo "Related PRs:"
          cat related-prs.txt

      - name: Generate execution plan with Copilot CLI
        id: copilot_plan
        env:
          GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
        run: |
          echo "ðŸ“‹ Generating execution plan with Copilot CLI..."

          # Read context
          TITLE=$(cat issue_title.txt)
          BODY=$(cat issue_body.txt)
          SIMILAR_ISSUES=$(cat similar-issues.txt)
          RELATED_PRS=$(cat related-prs.txt)

          # Load external prompt template and substitute variables
          sed -e "s|{{ISSUE_NUMBER}}|${{ github.event.issue.number }}|g" \
              -e "s|{{ISSUE_TITLE}}|${TITLE}|g" \
              -e "s|{{ISSUE_BODY}}|${BODY}|g" \
              -e "s|{{SIMILAR_ISSUES}}|${SIMILAR_ISSUES}|g" \
              -e "s|{{RELATED_PRS}}|${RELATED_PRS}|g" \
              .github/prompts/planning-instructions.md > planning_instructions.txt

          # Run Copilot CLI with external instructions
          copilot -p @planning_instructions.txt > execution_plan.txt

          echo "âœ… Execution plan generated"
          cat execution_plan.txt

      - name: Post execution plan
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Read the plan
          PLAN=$(cat execution_plan.txt)

          # Post as comment with approval prompt
          gh api POST /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            --input - <<EOF
          {
            "body": "## ðŸ¤– Phase 2: Execution Plan Ready\n\n${PLAN}\n\n---\n\n### Next Steps\n\nðŸ‘¤ **Human review required:** Please review the execution plan above.\n\n**To approve and proceed to implementation:**\nComment \`/approve-plan\` on this issue\n\n**To request changes:**\nComment with your requested modifications\n\n---\n*Automated by [agentic-journey Phase 2](https://github.com/${{ github.repository }}/tree/main/tech-talks/agentic-journey)*"
          }
          EOF

      - name: Update issue labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Remove triaged label, add planned label
          gh api DELETE /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/status:triaged || true

          gh api POST /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
            --input - <<EOF
          {
            "labels": ["status:planned"]
          }
          EOF

          echo "âœ… Execution plan ready for approval"
